setup:
  method: GS-WGAN
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: null
public_data:
  name: null
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: dataset/mnist/train_28.zip
  test_path: dataset/mnist/test_28.zip
  fid_stats: dataset/mnist/fid_stats_28.npz
model:
  ckpt: null
  num_discriminators: 1000
  c: 1
  Generator:
    z_dim: 10
    g_shared_dim: 128
    g_conv_dim: 64
    attn_g_loc:
    - 2
    apply_attn: true
  img_size: 28
  latent_type: bernoulli
  private_num_classes: 10
  public_num_classes: 1000
pretrain:
  log_dir: null
  seed: 0
  batch_size: 32
  iterations: 2000
  critic_iters: 5
  L_epsilon: 0.001
  L_gp: 10
  print_step: 100
  vis_step: 1000
  save_step: 5000
  cond: true
train:
  pretrain:
    log_dir: null
    label_random: false
    seed: 0
    batch_size: 32
    iterations: 2000
    critic_iters: 5
    L_epsilon: 0.001
    L_gp: 10
    print_step: 100
    vis_step: 1000
    save_step: 5000
    njobs: 10
  log_dir: null
  seed: 0
  batch_size: 32
  iterations: 20000
  critic_iters: 5
  L_epsilon: 0.001
  L_gp: 10
  print_step: 100
  vis_step: 1000
  save_step: 5000
  dp:
    epsilon: 10.0
    delta: 1e-5
    privacy_history: null
  n_splits: 1
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
  mode: val
