setup:
  method: dpsgd-lora
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dpdm/mnist_28_eps1.0
public_data:
  name: imagenet
  num_channels: 3
  resolution: 32
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: eurosat
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: dataset/eurosat/train_32.zip
  test_path: dataset/eurosat/test_32.zip
  fid_stats: dataset/eurosat/fid_stats_32.npz
model:
  ckpt: null
  network:
    attn_resolutions:
    - 16
    - 8
    - 4
    ch_mult:
    - 1
    - 2
    - 2
    nf: 32
pretrain:
  log_dir: null
  autoencoder:
    n_epochs: 4
    batch_size: 64
    config_path: ./models/DP_LDM/configs/autoencoder/autoencoder_kl_32.yaml
  unet:
    n_epochs: 160
    batch_size: 1024
    config_path: ./models/DP_LDM/configs/latent-diffusion/32_4M.yaml
  cond: true
train:
  config_path: ./models/DP_LORA/configs/finetuning/32_4M.yaml
  log_dir: null
  seed: 0
  batch_size: 4096
  n_epochs: 150
  dp:
    sdq: null
    max_grad_norm: 0.001
    delta: 1e-5
    epsilon: 10.0
    max_physical_batch_size: 8192
  n_splits: 32
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
  mode: val
