model:
  base_learning_rate: 1.0e-06
  target: models.DP_LDM.ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 3
    lossconfig:
      target: models.DP_LDM.ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 1.0e-06
        disc_weight: 0.5
    ddconfig:
      double_z: true
      z_channels: 3
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      num_res_blocks: 2
      attn_resolutions:
      - 16
      - 8
      dropout: 0.0
data:
  target: models.DP_LDM.main.DataModuleFromConfig
  params:
    batch_size: 1024
    num_workers: 32
    wrap: false
    train:
      target: data.SpecificImagenet.SpecificClassImagenet
      params:
        root: null
        split: train
        image_size: 28
        c: 1
    validation:
      target: data.SpecificImagenet.SpecificClassImagenet
      params:
        root: null
        split: train
        image_size: 28
        c: 1
lightning:
  trainer:
    max_epochs: 2
