setup:
  method: DP-MERF
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: null
public_data:
  name: null
  num_channels: 3
  resolution: 32
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: cifar100
  num_channels: 3
  resolution: 32
  n_classes: 100
  train_path: dataset/cifar100/train_32.zip
  test_path: dataset/cifar100/test_32.zip
  fid_stats: dataset/cifar100/fid_stats_32.npz
model:
  img_size: 32
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 60
    attn_g_loc:
    - 2
    apply_attn: true
  n_feat: 3072
  d_rff: 10000
  rff_sigma: '105'
  mmd_type: sphere
  private_num_classes: 100
  public_num_classes: 1000
  ckpt: null
pretrain:
  log_dir: null
  epochs: 5
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  cond: true
train:
  epochs: 5
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  log_dir: null
  num_channels: 3
  resolution: 32
  dp:
    epsilon: 1.0
    delta: 1e-5
    privacy_history: null
  n_splits: 1
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 3
  resolution: 32
eval:
  batch_size: 1000
  mode: val
