setup:
  method: DP-NTK
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: null
public_data:
  name: null
  num_channels: 3
  resolution: 32
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: camelyon_32
  num_channels: 3
  resolution: 32
  n_classes: 2
  train_path: dataset/camelyon/train_32.zip
  test_path: dataset/camelyon/test_32.zip
  fid_stats: dataset/camelyon/fid_stats_32.npz
model:
  model_ntk: fc_2l
  ntk_width: 32
  ntk_width2: 256
  img_size: 32
  c: 3
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 60
    attn_g_loc:
    - 2
    apply_attn: true
  private_num_classes: 2
  public_num_classes: 1000
  ckpt: null
pretrain:
  log_dir: null
  n_iter: 4000
  batch_size: 5000
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  cond: true
  n_splits: 8
train:
  n_iter: 2000
  batch_size: 5000
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  log_dir: null
  dp:
    epsilon: 10.0
    delta: 1e-6
    privacy_history: null
  n_splits: 8
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
  mode: val
