setup:
  method: dpsgd-gan
  run_type: torchmp
  n_gpus_per_node: 3
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6024
  omp_n_threads: 8
  workdir: null
public_data:
  name: null
  num_channels: 3
  resolution: 32
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: null
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: null
  test_path: null
  fid_stats: null
model:
  ema_rate: 0.999
  img_size: 32
  num_classes: 10
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 60
    attn_g_loc:
    - 2
    apply_attn: true
  Discriminator:
    d_conv_dim: 80
  private_num_classes: 10
  public_num_classes: 1000
  ckpt: null
pretrain:
  log_dir: null
  seed: 0
  batch_size: 1024
  snapshot_batch_size: 80
  fid_batch_size: 256
  n_epochs: 160
  d_updates: 5
  log_freq: 100
  snapshot_freq: 100
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 200
  fid_samples: 5000
  fid_threshold: 1
  cond: true
  optim:
    optimizer: Adam
    params:
      d_lr: 5e-4
      g_lr: 2e-4
      beta1: 0.0
train:
  log_dir: null
  seed: 0
  batch_size: 4096
  snapshot_batch_size: 80
  fid_batch_size: 256
  n_epochs: 150
  d_updates: 5
  log_freq: 10
  snapshot_freq: 10
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 20
  fid_samples: 5000
  final_fid_samples: 60000
  fid_threshold: 1
  optim:
    optimizer: Adam
    params:
      d_lr: 5e-4
      g_lr: 2e-4
      beta1: 0.0
  dp:
    privacy_history: null
    max_grad_norm: 0.001
    delta: 1e-5
    epsilon: 10.0
    max_physical_batch_size: 8192
  n_splits: 32
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
  mode: val
