setup:
  method: DP-Kernel
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: null
public_data:
  name: null
  num_channels: 3
  resolution: 32
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: cifar10
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: dataset/cifar10/train_32.zip
  test_path: dataset/cifar10/test_32.zip
  fid_stats: dataset/cifar10/fid_stats_32.npz
model:
  image_size: 32
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 60
    attn_g_loc:
    - 2
    apply_attn: true
  sigma_list:
  - 1
  - 2
  - 4
  - 8
  - 16
  private_num_classes: 10
  public_num_classes: 1000
  ckpt: null
pretrain:
  log_dir: null
  n_epochs: 1
  lr: 5e-5
  batch_size: 60
  cond: true
  n_splits: 8
train:
  max_iter: 200002
  batch_size: 60
  lr: 5e-5
  vis_step: 10000
  log_dir: null
  dp:
    epsilon: 10.0
    delta: 1e-5
    privacy_history: null
  n_splits: 1
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
  mode: val
